spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect

#uat
#BASEURL= https://10.51.135.27/
#BASEURL= https://intramashery.suryodaybank.co.in/
BASEURL= https://intramashery.suryodaybank.com/ssfb/
BASEURLLB= https://intramasherylb.suryodaybank.com/ssfb/
BASEURLV2=https://intramashery.suryodaybank.com/
BASEURL1= https://intramashery.suryodaybank.com/
BASEURLV3=https://surapiuat.suryodaybank.com/
LDAPURLDC=ldap://10.20.34.11:389
api_key=twkmgdbequkp827u8zdqe5bm
#BASEURLV3=https://intramashery.suryodaybank.com/ssfb/
#LDAPURLDR=ldap://10.40.34.11:389
#api_key=kyqak5muymxcrjhc5q57vz9v

CONSENT=Y
#BASEURLLOCAL=https://10.20.50.70:8443/
#BASEURL= https://intramashery.suryodaybank.com/ssfb/
#BASEURLV2= https://intramashery.suryodaybank.com/
TABENV=PROD
Logo=D:\\FInalUAT\\src\\main\\resources\\static\\
#Logo=/opt/SURYODAYFD/apache-tomcat-9.0.37/temp/
#temp=/opt/SURYODAYFD/apache-tomcat-9.0.37/temp/
temp=D:\\Web\\



# UATR
#spring.datasource.url=jdbc:sqlserver://10.51.133.26;databaseName=branch_digitisation
#spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
#spring.datasource.username=APPADMIN
#spring.datasource.password=APPADMIN@123^@!#$%!

#205 true
#204 false

scheduler.enabled=false
#working new production server
#spring.config.import=file:/APP/apache-tomcat-9.0.109/properties/application_digital.properties


#spring.datasource.url=jdbc:sqlserver://10.20.65.14:19444;databaseName=SURYODAYFD_NEW;encrypt=false;sslProtocol=TLSv1.2;useLOBs=false
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
#spring.datasource.username=SURYODAYFDUSER
#spring.datasource.password=Cib@123


#RAVI LOCAL CODE
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=loan_input;encrypt=false;useLOBs=false
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.datasource.username=ravi
spring.datasource.password=Ravi@1234



#nested exception is javax.management.InstanceAlreadyExistsException: com.zaxxer.hikari:name=dataSource,type=HikariDataSource
spring.jmx.default-domain=12343
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
multipart.enabled=true  


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


server.port=8081
#spring.jpa.properties.hibernate.jdbc.batch_size = 50
#spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.jdbc.batch_size = 50
spring.jpa.properties.hibernate.order_inserts = true   #number of 
spring.jpa.properties.hibernate.order_updates = true
#spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false 
#spring.jpa.properties.hibernate.type=trace
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate: ERROR

#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace


# Disabling the /v3/api-docs endpoint
springdoc.api-docs.enabled=true
# Paths to include
springdoc.pathsToMatch=/v1/*

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

#logging.level.root=WARN
logging.level.com.suryoday=debug
logging.level.org.springframework.web: debug

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.timeout=600s
spring.h2.console.enabled=true
logging.level.org.springframework.boot.test.json=ERROR


